name: bank_dash
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #For Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_utils: ^2.8.7

  #For Services locator
  get_it: ^7.6.7

  #For State Management
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4

  #For Ui
  dots_indicator: ^3.0.0
  flutter_svg: ^2.0.10+1
  loading_animation_widget: ^1.2.1

  #Others
  device_info_plus: ^9.1.1
  logger: ^2.1.0
  device_preview: ^1.1.0
  syncfusion_flutter_charts: ^27.1.56
  fl_chart: ^0.69.0
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/
    - assets/temp/
    - assets/gif/

  fonts:
    - family: Inter_18pt
      fonts:
        - asset: assets/fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700

    - family: Inter_24pt
      fonts:
        - asset: assets/fonts/Inter_24pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700

    - family: Inter_28pt
      fonts:
        - asset: assets/fonts/Inter_28pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_28pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 700

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lato-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700

    - family: Mont-Heavy-DEMO
      fonts:
        - asset: assets/fonts/Mont-Heavy-DEMO.otf





flutter_intl:
  class_name: MyLocalization
  arb_dir: assets/translation
  output_dir: lib/src/app/gen_localization
  enabled: true

# flutter_assets:
#   assets_path:
#     - assets/images/
#     - assets/svg/
#   output_path: lib/src/core/resources/
#   filename: assets.dart
#   field_prefix:
#   classname: R
#   ignore_comments: true
